// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5ObBC-8-SXFuLEnpH_iTLdQCNtjoX02w',
    appId: '1:53528033201:web:0deff38c3439536f59ef90',
    messagingSenderId: '53528033201',
    projectId: 'biology-ad330',
    authDomain: 'biology-ad330.firebaseapp.com',
    storageBucket: 'biology-ad330.appspot.com',
    measurementId: 'G-6VE38J2N1B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxokwIZG4OC02Wyu1CuHtYJ3qjYATX7q0',
    appId: '1:53528033201:android:ac7da210e62f26d059ef90',
    messagingSenderId: '53528033201',
    projectId: 'biology-ad330',
    storageBucket: 'biology-ad330.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTt7fpbd4y0OyqMdGAJJ7cbda0huciI68',
    appId: '1:53528033201:ios:a66a933d2f128d6559ef90',
    messagingSenderId: '53528033201',
    projectId: 'biology-ad330',
    storageBucket: 'biology-ad330.appspot.com',
    iosClientId: '53528033201-k4df35dh0rq22dgraeko85k0ig6h8u5n.apps.googleusercontent.com',
    iosBundleId: 'com.example.bio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTt7fpbd4y0OyqMdGAJJ7cbda0huciI68',
    appId: '1:53528033201:ios:a66a933d2f128d6559ef90',
    messagingSenderId: '53528033201',
    projectId: 'biology-ad330',
    storageBucket: 'biology-ad330.appspot.com',
    iosClientId: '53528033201-k4df35dh0rq22dgraeko85k0ig6h8u5n.apps.googleusercontent.com',
    iosBundleId: 'com.example.bio',
  );
}
